<?php

namespace Tests\Feature;

use App\Thread;
use function create;
use Illuminate\Support\Facades\Redis;
use function json_decode;
use Tests\TestCase;
use Illuminate\Foundation\Testing\DatabaseMigrations;

class TrendingThreadsTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Redis::del('trending_threads');
    }

    /**
     * It Increments A Threads Score Each time It is Read
     *
     * @test
     * @return void
     */
    public function itIncrementsAThreadsScoreEachTimeItIsRead()
    {
        $this->assertEmpty(Redis::zrevrange('trending_threads', 0, -1));

       $thread = create(Thread::class);

       $this->call('GET', $thread->path());

       $trending = Redis::zrevrange('trending_threads', 0, -1);

        $this->assertCount(1, $trending);

        $this->assertEquals($thread->title, json_decode($trending[0])->title);
    }
}